apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  project: advanced-devops-challenge

resources:
  - api/deployment.yaml
  - api/service.yaml
  - api/configmap.yaml
  - worker/deployment.yaml
  - worker/service.yaml
  - worker/configmap.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml
